### ISSUE TITLE
Crashes On Inject

### ISSUE THREAD

**Issue by arrayffs** [SomePineaple/Phantom#10]
Eh i think im doing something wrong but i am clueless at this point, even getting the libraries was a challenge for me, could someone help me please? This is minecraft's crash report
https://www.toptal.com/developers/hastebin/pebinitagi.yaml

**Comment by SomePineaple** [comment]
What version of minecraft are you running? Make sure its 1.8.9 forge, and if your already running that please tell me what mods you have installed.

**Comment by arrayffs** [comment]
i am running it and im using:
![Screenshot from 2022-05-14 18-33-17](https://user-images.githubusercontent.com/63004877/168440626-e424076b-e71e-4aeb-bc84-6bbeea331ee5.png)
The autogg is skilled v3

**Comment by SomePineaple** [comment]
sk1ers mods screw w/ minecraft mappings and cause crashes, u might have to find replacements for some of those.
