### ISSUE TITLE
My issue got closed for some reason

### ISSUE THREAD

**Issue by arrayffs** [SomePineaple/Phantom#11]
Im not sure if that was done manually or not, but if i could get an explanation it would be really nice

Basically my minecraft crashes on inject

**Comment by arrayffs** [comment]
This is the modpack btw
![Uploading Screenshot from 2022-05-14 18-33-17.png…]()

**Comment by SomePineaple** [comment]
I told u why, its bcuz ur using sk1ers modcore mods, which change minecraft mappings, causing it to crash. You'll have to switch mods.

**Comment by arrayffs** [comment]
sorry im dumbass and forgot to look inside closed issues :D my bad
