### ISSUE TITLE
Incompability issues with LabyMod

### ISSUE THREAD

**Issue by real-F-00** [SomePineaple/Phantom#3]
Upon trying to inject the process the following error returns:

`The target process unexpectedly stopped by signal 11.`

System Specs:

- Kernel: 5.13.0-35-generic
- GPU: NVIDIA GeForce GTX 1060 6GB, Drivers: Proprietary 470.103.01-0ubuntu0.20.04.1
- CPU: AMD Ryzen 5 5600X (12) @ 3.700G

Minecraft Setup:

- Launcher: MultiMC 5 Version 0.6.14-2998
- Forge Version: 11.15.1.2318
- Java Version: OpenJDK 64-Bit Server VM version 1.8.0_312

**Comment by SomePineaple** [comment]
Can you send me some more info? It would be useful to know exactly what mods your using, as well as how you injected the client (what program did you use to inject) and a more complete crash report would be very useful.

**Comment by ghost** [comment]
I'm pretty sure labymod does some weird things to the forge mappings, this might just be the standalone client version not the .jar mod though

**Comment by SomePineaple** [comment]
Yea if its laby mod then at the moment i'm not really bothered, I just try and avoid those mods

**Comment by ghost** [comment]
@real-F-00 I have a feeling if you use the normal minecraft launcher with forge + laby mod this would work, as on my own client i was having issues with MultiMC

**Comment by real-F-00** [comment]
> @real-F-00 I have a feeling if you use the normal minecraft launcher with forge + laby mod this would work, as on my own client i was having issues with MultiMC

weird, i know multimc does some patching stuff, but i don't think it would mess with mappings.
