### ISSUE TITLE
Error while trying to launch the injector 

### ISSUE THREAD

**Issue by MistyySoEpic** [SomePineaple/Phantom#5]
Everytime i run the injector i get this error:

./Phantom_Injector: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./Phantom_Injector)
./Phantom_Injector: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./Phantom_Injector)
./Phantom_Injector: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./Phantom_Injector)
./Phantom_Injector: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./Phantom_Injector)

How do i fix this?

**Comment by SomePineaple** [comment]
What distro are you running? Can you also send me some more information like what kernel your running, and also make sure that you are 100% up to date.

**Comment by SomePineaple** [comment]
Works when building from source.
