### ISSUE TITLE
CMakeLists.txt

### ISSUE THREAD

**Issue by ghost** [SomePineaple/Phantom#6]
![image](https://user-images.githubusercontent.com/84446427/163752404-4f1c53d6-5185-4e1e-8e2f-b28c7eadff02.png)
This seems like a massive pain to do! you can do some automated things in cmake: 
```
src/*.c*
```
this will fetch any files in `src/` with any title and the extensions starting with `.c*` ie `.cpp` and `cc` and `.c` now you can also fetch folders inside folders
```
src/*/*.c*
src/*/*/*.c*
src/*/*/*/*.c*
```
and so on to how many paths it goes in
I'm pretty sure theres a way to do looping in cmake directories but I'm quite new
I just thought it would be more nicer not having to set every files name

Side note, since you're including .h files you could just do `*.*`

I'm sorry I haven't made a pull request for this, when I'm free and remember I will! :)

**Comment by ghost** [comment]
I've created https://github.com/SomePineaple/Phantom/pull/7 if you want to check it out

**Comment by SomePineaple** [comment]
Merged #7
