### ISSUE TITLE
display glitch

### ISSUE THREAD

**Issue by ghost** [SomePineaple/Phantom#8]
when i inject the client it glitches my display going blank for a secend and going back when i move my mouse and after all my windows animations are gone till i close it
and it does this
![image](https://user-images.githubusercontent.com/91489868/164076900-e25bb230-6a0e-4d0e-9e9a-411c23129e66.png)

**Comment by SomePineaple** [comment]
Are you on KDE? If so, then thats a thing KDE does with applications using SDL2 or GLFW, which this is. You can stop this from happening by going to System Settings > Display and Monitor > Compositor, and un-checking the "Allow applications to block compositing" box
![setting](https://user-images.githubusercontent.com/69259448/164090074-debcc6e4-4911-4a48-98ab-8e9c82a96e54.png)
. If your not on KDE, or this doesn't fix, please let me know. If this fixes it, please close the issue.
